export const PROJECT = [
    {
        id: 1,
        title: "cnftTop Website",
        description: "As a creative portfolio project, I built a simple website for showing off digital art NFT projects. I did some experimentation with CSS here, and would like to refine it to include better content, best-practices with respect to code, and completed navigational pages.",
        coverImg: "images/cnft-top.png",
        link: "https://main--imaginative-pothos-1591fb.netlify.app/",
        //"https://youtu.be/eM5Gqr_QZQk",
        // embed: <iframe className="iframe-embedded-video" src="https://www.youtube.com/embed/eM5Gqr_QZQk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="true"></iframe>,
        // hoverText: "Click to watch a short video demonstrating the functionality of this website",
        alt: "Link to show functionality of my cnft website project",
        website: true,
    },
    {
        id: 2,
        title: "D&D Website",
        description: "",
        coverImg: "images/dnd.png",
        link: "https://youtu.be/yg5eJtQf_0c",
        embed: <iframe className="iframe-embedded-video" src="https://www.youtube.com/embed/yg5eJtQf_0c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="true"></iframe>,
        hoverText: "Click to watch a short video demonstrating the functionality of this website",
        alt: "Video to show functionality of my D&D website project",
        website: false,
    },
    {
        id: 3,
        title: "Tenzies Game",
        description: "",
        coverImg: "images/tenzies.png",
        link: "https://main--cheery-boba-18f328.netlify.app/",
        // "https://youtu.be/Tvqb91-Q7eA"
        alt: "Link to show functionality of my tenzies game project",
        website: true,
    },
    {
        id: 4,
        title: "1st Bootstrap Site",
        description: "This was my first bootstrap portfolio website",
        coverImg: "images/drunken-dragon.png",
        link: "https://dndnftgame.com/",
        alt: "iframe link to show functionality of my meme generator website project",
        website: true,
    },
    {
        id: 5,
        title: "Meme Generator",
        description: "",
        coverImg: "images/meme-generator.png",
        link: "https://youtu.be/38K8db9JjmA",
        embed: <iframe className="iframe-embedded-video" src="https://www.youtube.com/embed/38K8db9JjmA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="true"></iframe>,
        alt: "Video to show functionality of my meme generator website project",
        website: false, /*keep as video */
    },
    {
        id: 6,
        title: "Nucampsite Mobile App",
        description: "",
        coverImg: "images/react-native-mobile-app.png",
        link: "https://youtu.be/A-d6ugHbLbk",
        embed: <iframe className="iframe-embedded-video" src="https://www.youtube.com/embed/A-d6ugHbLbk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="true"></iframe>,
        alt: "Video to show functionality of my Nucampsite mobile app project",
        website: false,
    },
    {
        id: 7,
        title: "Airbnb Landing Page",
        description: "",
        coverImg: "images/airbnb-clone.png",
        embed: <img src="images/airbnb-clone.png" width="80%" height="80%"></img>,
        // link: "https://drive.google.com/file/d/1_P1E0ZWthQsYKmlDokDLXKVOQCpehDnl/view?usp=sharing",
        alt: "Image to show the display of my Airbnb landing page project",
        website: false,
        websiteImage: true,
    },
    {
        id: 8,
        title: "Digital Business Card",
        description: "",
        coverImg: "images/digital-business-card.png",
        link: "https://phenomenal-strudel-74df06.netlify.app/",
        // link: "https://drive.google.com/file/d/1dO7T4Kq1NJ1lRPXCvDgjYc0nDgV0CoqK/view?usp=sharing",
        alt: "Image to show the display of my digital business card project",
        website: true,
    },
]
