export const PROJECT = [
    {
        id: 1,
        title: "cnftTop Website",
        description: "As a creative portfolio project, I built a simple website for showing off digital art NFT projects. I did some experimentation with CSS here, and would like to refine it to include better content, best-practices with respect to code, and completed navigational pages.",
        coverImg: "images/cnft-top.png",
        link: "https://youtu.be/eM5Gqr_QZQk",
        hoverText: "Click to watch a short video demonstrating the functionality of this website",
        alt: "Video to show functionality of my cnft website project",
    },
    {
        id: 2,
        title: "D&D Website",
        description: "",
        coverImg: "images/dnd.png",
        link: "https://youtu.be/yg5eJtQf_0c",
        alt: "Video to show functionality of my D&D website project",
    },
    {
        id: 3,
        title: "Tenzies Game",
        description: "",
        coverImg: "images/tenzies.png",
        link: "https://youtu.be/Tvqb91-Q7eA",
        alt: "Video to show functionality of my tenzies game project",
    },
    {
        id: 4,
        title: "1st Bootstrap Site",
        description: "This was my first bootstrap portfolio website",
        coverImg: "images/drunken-dragon.png",
        link: "https://dndnftgame.com/",
        alt: "Video to show functionality of my meme generator website project",
    },
    {
        id: 5,
        title: "Meme Generator",
        description: "",
        coverImg: "images/meme-generator.png",
        link: "https://youtu.be/38K8db9JjmA",
        alt: "Video to show functionality of my meme generator website project",
    },
    {
        id: 6,
        title: "Nucampsite Mobile App",
        description: "",
        coverImg: "images/react-native-mobile-app.png",
        link: "https://youtu.be/A-d6ugHbLbk",
        alt: "Video to show functionality of my Nucampsite mobile app project",
    },
    {
        id: 7,
        title: "Airbnb Landing Page",
        description: "",
        coverImg: "images/airbnb-clone.png",
        link: "https://drive.google.com/file/d/1_P1E0ZWthQsYKmlDokDLXKVOQCpehDnl/view?usp=sharing",
        alt: "Image to show the display of my Airbnb landing page project",
    },
    {
        id: 8,
        title: "Digital Business Card",
        description: "",
        coverImg: "images/digital-business-card.png",
        link: "https://drive.google.com/file/d/1dO7T4Kq1NJ1lRPXCvDgjYc0nDgV0CoqK/view?usp=sharing",
        alt: "Image to show the display of my digital business card project",
    },
]
